import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";

import { salaryApi } from "@career-os/shared";
import { seoPageMetadata, titleCaseSlug } from "../../seo-utils";

type Props={params:{role:string}};
async function load(role:string){try{const result=await salaryApi.benchmark(role,"India");return result.available&&result.benchmark?result:null}catch{return null}}
export async function generateMetadata({params}:Props):Promise<Metadata>{const result=await load(params.role);const role=result?.benchmark?.role??titleCaseSlug(params.role);if(!result)return{title:"Salary benchmark unavailable | Jobs View",robots:{index:false,follow:true}};return seoPageMetadata(`${role} Salary in India`, `Reviewed ${role} salary evidence for India with source, effective date, sample size and confidence.`, `/salary/${params.role}`)}
export default async function SalaryRolePage({params}:Props){const result=await load(params.role);if(!result?.benchmark)notFound();const b=result.benchmark;return <main className="mx-auto max-w-4xl px-4 py-10 sm:px-6"><p className="text-sm font-bold text-[var(--cos-primary)]">Reviewed salary benchmark</p><h1 className="mt-2 text-3xl font-extrabold sm:text-4xl">{b.role} salary in India</h1><p className="mt-4 leading-7 text-[var(--cos-on-surface-variant)]">This market estimate is based on {b.source.name} and is not guaranteed compensation.</p><div className="mt-8 grid gap-4 sm:grid-cols-3"><Metric label="25th percentile" value={money(b.p25_annual)}/><Metric label="Median" value={money(b.median_annual)}/><Metric label="75th percentile" value={money(b.p75_annual)}/></div><dl className="mt-8 grid gap-4 rounded-md border border-[var(--cos-outline-variant)] p-5 sm:grid-cols-2"><Fact label="Geography" value={`${b.geography} (${b.geography_level})`}/><Fact label="Confidence" value={b.confidence}/><Fact label="Sample size" value={b.sample_size?String(b.sample_size):"Not disclosed"}/><Fact label="Effective date" value={new Date(b.effective_date).toLocaleDateString("en-IN")}/></dl>{result.stale?<p className="mt-4 rounded-md border border-amber-500 p-4 text-sm">This benchmark is older than 13 months. Review the source date before using it.</p>:null}<section className="mt-8"><h2 className="text-xl font-bold">Source and methodology</h2><p className="mt-3 leading-7 text-[var(--cos-on-surface-variant)]">{b.source.methodology}</p><a href={b.source.url} target="_blank" rel="noreferrer" className="mt-3 inline-block font-bold text-[var(--cos-primary)] hover:underline">Open {b.source.publisher} source</a></section><div className="mt-8 flex flex-wrap gap-4"><Link className="rounded-md bg-[var(--cos-primary)] px-5 py-3 font-bold text-white" href={`/jobs?q=${encodeURIComponent(b.role)}`}>View live jobs</Link><Link className="rounded-md border border-[var(--cos-outline-variant)] px-5 py-3 font-bold" href="/salary/methodology">Read methodology</Link></div></main>}
function money(value?:number){return value?new Intl.NumberFormat("en-IN",{style:"currency",currency:"INR",maximumFractionDigits:0}).format(value)+" / year":"Not reported"}
function Metric({label,value}:{label:string;value:string}){return <div className="rounded-md border border-[var(--cos-outline-variant)] p-5"><div className="text-sm text-[var(--cos-on-surface-variant)]">{label}</div><div className="mt-2 text-xl font-extrabold">{value}</div></div>}
function Fact({label,value}:{label:string;value:string}){return <div><dt className="text-sm text-[var(--cos-on-surface-variant)]">{label}</dt><dd className="mt-1 font-bold capitalize">{value}</dd></div>}
