"use client";

import Image from "next/image";
import Link from "next/link";
import { useRouter } from "next/navigation";
import React from "react";
import { FormEvent, useCallback, useEffect, useRef, useState } from "react";
import { motion, useReducedMotion } from "framer-motion";
import { useQuery } from "@tanstack/react-query";
import { ArrowRight, Bell, BookOpen, Briefcase, Building2, Calculator, ChevronDown, Menu, Moon, Search, Sun, UserRound, X } from "lucide-react";

import { appConfig } from "@career-os/config";
import { apiErrorMessage, companyApi, jobsApi, type PublicCompany, type PublicJob, useAuthStore, useThemeStore } from "@career-os/shared";
import { Badge, Button, Card, EmptyState, JobCard, SkeletonCard } from "@career-os/ui";
import { cn } from "@career-os/utils";
import { publicRoutes } from "../../content/public-routes";
import { AudienceChooser } from "./audience-chooser";

const container = "mx-auto max-w-7xl px-4 sm:px-6 lg:px-8";
const focus = "focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[var(--cos-primary)] focus-visible:ring-offset-2";
const roleCards = [
  ["Driver jobs", "driver", "10th pass and licence-based roles"], ["Delivery jobs", "delivery executive", "Flexible delivery and quick-commerce work"],
  ["Security jobs", "security guard", "Residential, office and industrial security"], ["Warehouse jobs", "warehouse associate", "Picking, packing and inventory roles"],
  ["Retail jobs", "retail associate", "Store, cashier and customer service work"], ["ITI jobs", "ITI technician", "Electrician, fitter and technical work"],
  ["Nursing home care job", "Nursing home care", "Patient care, elderly assistance and medical support"], ["Staff nurse job", "Staff nurse", "Hospital, clinic and ICU certified nursing positions"],
  ["Doctors job", "Doctors", "Medical officers, specialist consultants and physicians"], ["Work from home job", "Work from home", "Remote customer support, tech and desk operations"],
  ["Fresher jobs", "fresher", "First career opportunities, trainee programs and entry roles"], ["Experienced jobs", "experienced", "Senior lateral roles, team leads and technical specialists"]
] as const;
const employers = ["Swiggy", "Zomato", "SIS Limited", "Blinkit", "Zepto", "Delhivery", "Amazon", "Flipkart", "BigBasket", "Reliance Retail", "TCS", "Infosys"] as const;

export function PublicHome({ showAudienceChooser = false }: { showAudienceChooser?: boolean }) {
  const [chooserOpen, setChooserOpen] = useState(showAudienceChooser);
  const continueAsJobSeeker = useCallback(() => { document.cookie = "jobsview_audience=job; Path=/; SameSite=Lax"; setChooserOpen(false); }, []);
  return <><main id="main-content" tabIndex={-1} className="bg-[var(--cos-surface)] text-[var(--cos-on-surface)]"><Navbar /><Hero /><AudiencePaths /><LatestJobs /><EntryRoles /><PopularEmployers /><CareerTools /><EmployerCTA /><Footer /></main>{chooserOpen ? <AudienceChooser onContinue={continueAsJobSeeker} /> : null}</>;
}

export function Navbar() {
  const [explore, setExplore] = useState(false); const [servicesOpen, setServicesOpen] = useState(false); const [mobile, setMobile] = useState(false); const root=useRef<HTMLDivElement>(null);
  const mode=useThemeStore((state)=>state.mode);const setMode=useThemeStore((state)=>state.setMode);const user=useAuthStore((state)=>state.user);
  useEffect(()=>{const close=(event:MouseEvent)=>{if(!root.current?.contains(event.target as Node)){setExplore(false);setServicesOpen(false);setMobile(false)}};const key=(event:KeyboardEvent)=>{if(event.key==="Escape"){setExplore(false);setServicesOpen(false);setMobile(false)}};document.addEventListener("mousedown",close);document.addEventListener("keydown",key);return()=>{document.removeEventListener("mousedown",close);document.removeEventListener("keydown",key)}},[]);
  const close=()=>{setExplore(false);setServicesOpen(false);setMobile(false)};
  return <header className="sticky top-0 z-50 border-b border-[var(--cos-outline-variant)] bg-[var(--cos-surface-container-lowest)]/95 backdrop-blur"><div ref={root} className={cn(container,"flex min-h-16 items-center gap-3 py-2")}>
    <Link href="/" onClick={close} aria-label="Jobs View home" className={cn("relative h-12 w-14 shrink-0",focus)}><Image src="/images/logo-mark.png" fill sizes="56px" className="object-contain" alt="" priority /></Link>
    <nav className="hidden items-center gap-1 lg:flex" aria-label="Primary navigation">
      {publicRoutes.primary.map((route)=><Link key={route.href} href={route.href} className={cn("rounded-md px-3 py-2 text-sm font-semibold hover:bg-[var(--cos-surface-container-low)]",focus)}>{route.label}</Link>)}
      <div className="relative">
        <button onClick={()=>{setServicesOpen((value)=>!value);setExplore(false)}} className={cn("inline-flex min-h-10 items-center gap-1 rounded-md px-3 text-sm font-bold text-amber-600 dark:text-amber-400 hover:bg-[var(--cos-surface-container-low)]",focus)} aria-expanded={servicesOpen}>Our Services <ChevronDown size={15}/></button>
        {servicesOpen?<div className="absolute left-0 top-12 grid w-72 gap-1.5 rounded-lg border border-[var(--cos-outline-variant)] bg-[var(--cos-surface-container-lowest)] p-2.5 shadow-xl z-50">
          {publicRoutes.ourServices.map((route)=><Link key={route.href} href={route.href} onClick={close} className="rounded-md p-2 hover:bg-[var(--cos-surface-container-low)] transition flex flex-col gap-0.5"><span className="text-sm font-bold text-[var(--cos-primary)]">{route.label}</span>{route.description?<span className="text-xs text-[var(--cos-on-surface-variant)] line-clamp-1">{route.description}</span>:null}</Link>)}
        </div>:null}
      </div>
      <div className="relative">
        <button onClick={()=>{setExplore((value)=>!value);setServicesOpen(false)}} className={cn("inline-flex min-h-10 items-center gap-1 rounded-md px-3 text-sm font-semibold hover:bg-[var(--cos-surface-container-low)]",focus)} aria-expanded={explore}>Explore <ChevronDown size={15}/></button>
        {explore?<div className="absolute left-0 top-12 grid w-64 gap-1 rounded-md border border-[var(--cos-outline-variant)] bg-[var(--cos-surface-container-lowest)] p-2 shadow-lg z-50">{[...publicRoutes.explore,...publicRoutes.tools].map((route)=><Link key={route.href+route.label} href={route.href} onClick={close} className="rounded-md px-3 py-2 text-sm hover:bg-[var(--cos-surface-container-low)]">{route.label}</Link>)}</div>:null}
      </div>
    </nav>
    <button onClick={()=>window.dispatchEvent(new CustomEvent("jobsview:open-command-center"))} className={cn("ml-auto hidden min-h-10 min-w-52 items-center gap-2 rounded-full border border-[var(--cos-outline-variant)] px-4 text-sm text-[var(--cos-on-surface-variant)] md:flex",focus)}><Search size={16}/> Search <span className="ml-auto text-xs">Ctrl K</span></button>
    <Button variant="ghost" size="icon" aria-label="Change color theme" onClick={()=>setMode(mode==="dark"?"light":"dark")}>{mode==="dark"?<Sun size={17}/>:<Moon size={17}/>}</Button>
    {user?<><Link href="/notifications" aria-label="Notifications" className={cn("hidden rounded-md p-2 sm:inline-flex",focus)}><Bell size={18}/></Link><Link href="/candidate" className={cn("hidden items-center gap-2 rounded-md px-3 py-2 text-sm font-bold sm:inline-flex",focus)}><UserRound size={17}/> Dashboard</Link></>:<><Link href="/login" className="hidden px-2 py-2 text-sm font-bold sm:block">Login</Link><Link href="/register" className="hidden rounded-md bg-[var(--cos-primary)] px-4 py-2 text-sm font-bold text-white md:block">Register</Link></>}
    <Button variant="ghost" size="icon" className="lg:hidden" aria-label="Open navigation" onClick={()=>setMobile(true)}><Menu size={19}/></Button>
    {mobile?<div className="fixed inset-0 z-50 bg-slate-950/45"><aside className="ml-auto flex h-dvh w-[min(90vw,380px)] flex-col bg-[var(--cos-surface-container-lowest)] p-4"><div className="flex items-center justify-between"><strong>Menu</strong><Button variant="ghost" size="icon" aria-label="Close navigation" onClick={close}><X size={18}/></Button></div><nav className="mt-4 grid gap-1 overflow-auto"><div className="text-xs font-extrabold text-[var(--cos-primary)] px-3 py-1">Core Navigation</div>{publicRoutes.primary.map((route)=><Link key={route.href+route.label} href={route.href} onClick={close} className="min-h-11 flex items-center rounded-md px-3 font-semibold hover:bg-[var(--cos-surface-container-low)]">{route.label}</Link>)}<div className="text-xs font-extrabold text-[var(--cos-primary)] px-3 py-1 mt-2">Our Services</div>{publicRoutes.ourServices.map((route)=><Link key={route.href+route.label} href={route.href} onClick={close} className="min-h-11 flex items-center rounded-md px-3 font-bold text-amber-600 dark:text-amber-400 hover:bg-[var(--cos-surface-container-low)]">{route.label}</Link>)}<div className="text-xs font-extrabold text-[var(--cos-primary)] px-3 py-1 mt-2">Explore &amp; Tools</div>{[...publicRoutes.explore,...publicRoutes.tools].map((route)=><Link key={route.href+route.label} href={route.href} onClick={close} className="min-h-11 flex items-center rounded-md px-3 font-semibold hover:bg-[var(--cos-surface-container-low)]">{route.label}</Link>)}</nav><div className="mt-auto grid gap-2 border-t border-[var(--cos-outline-variant)] pt-4"><Link href="/login" onClick={close} className="rounded-md border p-3 text-center font-bold">Login</Link><a href={publicRoutes.employer.href} className="rounded-md bg-[var(--cos-primary)] p-3 text-center font-bold text-white">I want to hire</a></div></aside></div>:null}
  </div></header>;
}

function Hero(){const router=useRouter();const [q,setQ]=useState("");const [location,setLocation]=useState("");function submit(event:FormEvent){event.preventDefault();const params=new URLSearchParams();if(q.trim())params.set("q",q.trim());if(location.trim())params.set("location",location.trim());router.push(`/jobs${params.size?`?${params}`:""}`)}return <section className="border-b border-[var(--cos-outline-variant)]"><div className={cn(container,"grid min-h-[min(720px,calc(100svh-4rem))] items-center gap-8 py-12 lg:grid-cols-[1.1fr_.9fr]")}><Reveal><Badge tone="premium">Jobs for every stage</Badge><h1 className="mt-5 max-w-3xl text-4xl font-extrabold leading-tight sm:text-5xl lg:text-6xl">Find work you can trust. <span className="text-[var(--cos-accent)]">Build what comes next.</span></h1><p className="mt-5 max-w-2xl text-lg leading-8 text-[var(--cos-on-surface-variant)]">Search published opportunities for 10th and 12th pass candidates, ITI workers, freshers, graduates, and experienced professionals across India.</p><form onSubmit={submit} className="mt-7 grid gap-2 rounded-md border border-[var(--cos-outline-variant)] bg-[var(--cos-surface-container-lowest)] p-3 shadow-sm sm:grid-cols-[1fr_1fr_auto]"><label className="grid gap-1"><span className="text-xs font-bold">Job or skill</span><input value={q} onChange={(event)=>setQ(event.target.value)} className="h-12 min-w-0 rounded-md border border-[var(--cos-outline-variant)] bg-transparent px-3 outline-none focus:border-[var(--cos-primary)]" placeholder="Driver, accountant, React"/></label><label className="grid gap-1"><span className="text-xs font-bold">Location</span><input value={location} onChange={(event)=>setLocation(event.target.value)} className="h-12 min-w-0 rounded-md border border-[var(--cos-outline-variant)] bg-transparent px-3 outline-none focus:border-[var(--cos-primary)]" placeholder="City or remote"/></label><Button className="self-end sm:h-12"><Search size={17}/> Search jobs</Button></form><div className="mt-4 flex flex-wrap gap-2">{["10th pass","12th pass","ITI","Fresher","Experienced","Nursing home care","Staff nurse","Doctors","Work from home","Remote"].map((item)=><Link key={item} href={`/jobs?q=${encodeURIComponent(item)}`} className="rounded-full border border-[var(--cos-outline-variant)] px-3 py-1.5 text-sm font-semibold hover:border-[var(--cos-primary)]">{item}</Link>)}</div></Reveal><Reveal><div className="relative mx-auto aspect-[4/3] w-full max-w-xl overflow-hidden rounded-md"><Image src="/images/home-hero-india-careers.png" fill priority sizes="(max-width:1023px) 100vw, 45vw" className="object-cover" alt="Indian job seekers exploring career opportunities"/></div></Reveal></div></section>}

function AudiencePaths(){return <Section title="Choose the path that fits you"><div className="grid gap-4 md:grid-cols-2"><PathCard icon={<Search/>} title="I want a job" text="Browse jobs freely. Sign in only when you apply or use a member career tool." href="/jobs" action="Browse jobs"/><PathCard icon={<Building2/>} title="I want to hire" text="Post jobs, review candidates, and manage hiring from the employer workspace." href={publicRoutes.employer.href} action="Open employer portal"/></div></Section>}
function LatestJobs(){const query=useQuery({queryKey:["home","jobs"],queryFn:()=>jobsApi.search({sort:"latest",limit:6})});const jobs=asItems<PublicJob>(query.data);return <Section title="Latest jobs" description="Recently published opportunities from the live Jobs View marketplace." action={{label:"Browse all jobs",href:"/jobs"}}>{query.isPending?<div className="grid gap-4 md:grid-cols-2 lg:grid-cols-3">{[1,2,3].map((item)=><SkeletonCard key={item} lines={4}/>)}</div>:query.isError?<LoadError message={apiErrorMessage(query.error)} retry={()=>void query.refetch()}/>:jobs.length?<div className="grid gap-4 md:grid-cols-2 lg:grid-cols-3">{jobs.slice(0,6).map((job)=><JobCard key={job.id} title={job.title} company={job.company_name} location={[job.city,job.state].filter(Boolean).join(", ")||job.work_mode||"India"} salary={jobSalary(job)} tags={(job.skills??[]).slice(0,3).map((skill)=>skill.name)} href={`/jobs/${job.slug}`} status={job.is_urgent?<Badge tone="urgent">Urgent</Badge>:undefined}/>)}</div>:<EmptyState icon={<Briefcase/>} title="No published jobs yet" description="New opportunities will appear here after employers publish them." action={<Link href="/jobs" className="font-bold text-[var(--cos-primary)]">Browse job search</Link>}/>}</Section>}
function EntryRoles(){return <Section title="Explore Featured Jobs & Career Pathways" description="Direct routes into healthcare, frontline, remote work, entry-level fresher, and experienced professional roles."><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{roleCards.map(([title,query,description])=><Link key={query} href={`/jobs?q=${encodeURIComponent(query)}`} className={cn("rounded-md border border-[var(--cos-outline-variant)] p-5 transition hover:-translate-y-1 hover:border-[var(--cos-primary)]",focus)}><Briefcase className="text-[var(--cos-primary)]"/><h3 className="mt-4 text-lg font-bold">{title}</h3><p className="mt-2 text-sm leading-6 text-[var(--cos-on-surface-variant)]">{description}</p><span className="mt-4 inline-flex items-center gap-1 font-bold text-[var(--cos-primary)]">View jobs <ArrowRight size={15}/></span></Link>)}</div></Section>}
function PopularEmployers(){const query=useQuery({queryKey:["home","companies"],queryFn:()=>companyApi.search({limit:12})});const companies=asItems<PublicCompany>(query.data);return <Section title="Popular employers" description="Companies candidates commonly search for. This list does not imply endorsement or partnership." action={{label:"Explore companies",href:"/companies"}}><div className="overflow-hidden rounded-md border border-[var(--cos-outline-variant)] py-4"><div className="jobsview-partner-track flex w-max gap-3 px-3">{[...employers,...employers].map((name,index)=>{const match=companies.find((company)=>company.name.toLowerCase()===name.toLowerCase());const href=match?`/companies/${match.slug}`:`/jobs?company=${encodeURIComponent(name)}`;return <Link key={`${name}-${index}`} href={href} className="flex h-20 w-44 shrink-0 items-center gap-3 rounded-md border border-[var(--cos-outline-variant)] bg-[var(--cos-surface-container-lowest)] px-4 hover:border-[var(--cos-primary)]"><Image src={`/images/employers/${logoName(name)}.${logoExtension(name)}`} width={44} height={44} className="h-11 w-11 object-contain" alt=""/><span className="font-bold">{name}</span></Link>})}</div></div>{query.isError?<p className="mt-3 text-sm text-[var(--cos-on-surface-variant)]">Company profiles are temporarily unavailable; employer tiles open filtered job search.</p>:null}</Section>}
function CareerTools(){const tools=[{icon:<Calculator/>,title:"Salary calculator",text:"See source-backed market estimates with confidence and methodology.",href:"/salary/calculator"},{icon:<BookOpen/>,title:"Resume builder",text:"Preview five ATS-conscious templates before opening the Premium workspace.",href:"/resume-builder"},{icon:<UserRound/>,title:"Career guidance",text:"Start with practical guidance, then sign in for complete member resources.",href:"/guidance"}];return <Section title="Career tools"><div className="grid gap-4 md:grid-cols-3">{tools.map((tool)=><PathCard key={tool.title} {...tool} action="Open tool"/>)}</div></Section>}
function EmployerCTA(){return <section className="bg-[var(--cos-primary)] text-white"><div className={cn(container,"flex flex-col items-start justify-between gap-6 py-10 md:flex-row md:items-center")}><div><h2 className="text-3xl font-extrabold">Hiring for your team?</h2><p className="mt-2 max-w-2xl text-white/80">Create a company workspace, publish jobs, and manage applicants from one place.</p></div><a href={publicRoutes.employer.href} className="rounded-md bg-[var(--cos-accent)] px-5 py-3 font-bold text-slate-950">Open employer portal</a></div></section>}
export function Footer(){return <footer className="border-t border-[var(--cos-outline-variant)]"><div className={cn(container,"grid gap-8 py-10 sm:grid-cols-2 lg:grid-cols-6")}><div className="sm:col-span-2"><div className="relative h-14 w-16"><Image src="/images/logo-mark.png" fill className="object-contain" alt="Jobs View"/></div><p className="mt-3 max-w-sm text-sm leading-6 text-[var(--cos-on-surface-variant)]">Clear job discovery and practical career tools for India.</p></div><FooterGroup title="Explore" routes={[...publicRoutes.primary,...publicRoutes.explore]}/><FooterGroup title="Our Services" routes={publicRoutes.ourServices}/><FooterGroup title="Career tools" routes={publicRoutes.tools}/><FooterGroup title="Support" routes={[...publicRoutes.support,...publicRoutes.legal]}/></div><div className={cn(container,"border-t border-[var(--cos-outline-variant)] py-5 text-sm text-[var(--cos-on-surface-variant)] flex flex-col sm:flex-row items-center justify-between gap-3")}><div>&copy; 2026 Jobs View. Salary estimates are informational and are not guaranteed compensation.</div><div className="font-medium">Powered By <a href="https://gautamenterprises.org" target="_blank" rel="noopener noreferrer" className="font-bold text-[var(--cos-primary)] hover:underline">Gautam Tech Studio</a></div></div></footer>}


function Section({title,description,action,children}:{title:string;description?:string;action?:{label:string;href:string};children:React.ReactNode}){return <Reveal><section className={cn(container,"py-10 sm:py-14")}><div className="mb-6 flex flex-wrap items-end justify-between gap-3"><div><h2 className="text-2xl font-extrabold sm:text-3xl">{title}</h2>{description?<p className="mt-2 max-w-3xl text-[var(--cos-on-surface-variant)]">{description}</p>:null}</div>{action?<Link href={action.href} className="font-bold text-[var(--cos-primary)] hover:underline">{action.label}</Link>:null}</div>{children}</section></Reveal>}
function Reveal({children}:{children:React.ReactNode}){const reduced=useReducedMotion();return <motion.div initial={reduced?false:{opacity:0,y:18}} whileInView={{opacity:1,y:0}} viewport={{once:true,amount:.12}} transition={{duration:reduced?0:.32,ease:"easeOut"}}>{children}</motion.div>}
function PathCard({icon,title,text,href,action}:{icon:React.ReactNode;title:string;text:string;href:string;action:string}){const external=href.startsWith("http");const body=<><span className="inline-flex h-11 w-11 items-center justify-center rounded-md bg-[var(--cos-primary)] text-white">{icon}</span><h3 className="mt-4 text-xl font-bold">{title}</h3><p className="mt-2 leading-6 text-[var(--cos-on-surface-variant)]">{text}</p><span className="mt-5 inline-flex items-center gap-1 font-bold text-[var(--cos-primary)]">{action}<ArrowRight size={16}/></span></>;const classes=cn("rounded-md border border-[var(--cos-outline-variant)] bg-[var(--cos-surface-container-lowest)] p-6 transition hover:-translate-y-1 hover:border-[var(--cos-primary)]",focus);return external?<a href={href} className={classes}>{body}</a>:<Link href={href} className={classes}>{body}</Link>}
function FooterGroup({title,routes}:{title:string;routes:readonly {label:string;href:string}[]}){return <div><h2 className="font-bold">{title}</h2><ul className="mt-3 grid gap-2 text-sm">{routes.map((route)=><li key={`${route.href}-${route.label}`}><Link href={route.href} className="text-[var(--cos-on-surface-variant)] hover:text-[var(--cos-primary)] hover:underline">{route.label}</Link></li>)}</ul></div>}
function LoadError({message,retry}:{message:string;retry:()=>void}){return <Card role="alert" className="text-center"><h3 className="font-bold">This section could not be loaded</h3><p className="mt-2 text-sm text-[var(--cos-on-surface-variant)]">{message}</p><Button className="mt-4" onClick={retry}>Retry</Button></Card>}
function asItems<T>(value:unknown):T[]{if(Array.isArray(value))return value as T[];if(value&&typeof value==="object"&&"items" in value&&Array.isArray((value as {items:unknown}).items))return(value as {items:T[]}).items;return[]}
function jobSalary(job:PublicJob){if(job.salary_min==null&&job.salary_max==null)return undefined;const period=job.salary_period?` / ${job.salary_period.replace("ly","")}`:"";return `${job.currency||"INR"} ${Number(job.salary_min??job.salary_max).toLocaleString("en-IN")}${job.salary_min!=null&&job.salary_max!=null?` - ${Number(job.salary_max).toLocaleString("en-IN")}`:""}${period}`}
function logoName(name:string){return name.toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"")}
function logoExtension(name:string){return ["Swiggy","Zomato","BigBasket","TCS","Infosys"].includes(name)?"svg":"png"}
